#http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_rabbit_producer_properties

spring:
  application.name: producer-magneto
  rabbitmq:
    addresses: localhost
    virtual_host: xmen

  cloud:
    stream.bindings:
      XMenQueueOutput:
        destination: xmen-queue
        producer:
          requiredGroups: xmen-group

#    rabbit.bindings:
#        XMenQueueOutput:
#          producer:
#            bindQueue: false